package com.example.accessingdatamysql;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /api (after Application path)
public class MainController {
	// @Autowired // This means to get the bean called animalRepository
	// // Which is auto-generated by Spring, we will use it to handle the data
	// private AnimalRepository animalRepository;

	@GetMapping(path = "/guide")
	public @ResponseBody String guide() {
		return "Welcome to the Animal API! You can add, delete, and view animals.";
	}
}